-- Short-lived WebRTC signaling between users with an accepted Sync connection.
-- Media never passes through this table; only SDP offers/answers and call state do.

create table if not exists public.call_signals (
  id          bigint generated by default as identity primary key,
  call_id     uuid not null,
  sender_id   uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  kind        text not null check (kind in ('offer', 'answer', 'reject', 'end')),
  payload     jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now(),
  check (sender_id <> receiver_id)
);

alter table public.call_signals enable row level security;

drop policy if exists "Call signals are viewable by participants" on public.call_signals;
create policy "Call signals are viewable by participants"
  on public.call_signals for select
  using (auth.uid() = sender_id or auth.uid() = receiver_id);

drop policy if exists "Synced users can send call signals" on public.call_signals;
create policy "Synced users can send call signals"
  on public.call_signals for insert
  with check (
    auth.uid() = sender_id
    and exists (
      select 1
      from public.connections
      where status = 'accepted'
        and (
          (requester_id = sender_id and addressee_id = receiver_id)
          or (requester_id = receiver_id and addressee_id = sender_id)
        )
    )
  );

drop policy if exists "Participants can delete expired call signals" on public.call_signals;
create policy "Participants can delete expired call signals"
  on public.call_signals for delete
  using (
    (auth.uid() = sender_id or auth.uid() = receiver_id)
    and created_at < now() - interval '1 day'
  );

create index if not exists call_signals_receiver_created_idx
  on public.call_signals (receiver_id, created_at desc);
create index if not exists call_signals_call_idx
  on public.call_signals (call_id, created_at);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'call_signals'
  ) then
    alter publication supabase_realtime add table public.call_signals;
  end if;
end
$$;
